### ISSUE TITLE
Ability to remove date/time part from home

### ISSUE THREAD

**Issue by pnxtm** [whataudoinghere/CPL#13]
I am using another calendar system and really don't like the date/time part on my home screen and I can't find any option in the "Home Screen" section to hide it.
It's would be very good to have an option in the "Home Screen" section similar to "Add clock" so one can disable/enable displaying date/time part in home screen.

Thanks a lot.

**Comment by et304383** [comment]
I think you're looking to disable "at a glance" which can be found under home settings -> home screen.
